### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by mwcassens** [karlvr/homebridge-roomba2#163]
### Describe The Bug

The plugin fails to show the roomba accessories after upgrading to version 2.1.0

### To Reproduce

At version 2.0.0 both of my roomba accessories were reporting to homebridge.  After upgrading to version 2.1.0, and restarting the following error occurs:  plugin was found for the accessory "Roomba2" in your config.json. Please make sure the corresponding plugin is installed correctly. I attempted to rollback to version 2.0.0 but the same error occurs.  I had to roll back to version 1.5.3 to recover my roomba accessories. 

### Expected behavior

Choosing the upgrade to 2.1.0 should work without losing my Roomba accessories after I put in teh configuration information.

### Relevant log output

```shell
[37m[3/10/2025, 11:37:10 AM] [39m[31mNo plugin was found for the accessory "Roomba2" in your config.json. Please make sure the corresponding plugin is installed correctly.[39m
[37m[3/10/2025, 12:11:02 PM] [39mRegistering accessory '@homebridge-plugins/homebridge-roomba.Roomba2'
[37m[3/10/2025, 12:11:02 PM] [39m[36m[Rudi][39m Initializing Roomba2 accessory...
[37m[3/10/2025, 12:11:03 PM] [39m[36m[Rosie][39m Initializing Roomba2 accessory...
[37m[3/10/2025, 12:12:14 PM] [39mRegistering accessory '@homebridge-plugins/homebridge-roomba.Roomba2'
[37m[3/10/2025, 12:12:14 PM] [39m[36m[Rudi][39m Initializing Roomba2 accessory...
[37m[3/10/2025, 12:12:14 PM] [39m[36m[Rosie][39m Initializing Roomba2 accessory...
[37m[3/10/2025, 12:14:55 PM] [39mRegistering accessory '@homebridge-plugins/homebridge-roomba.Roomba2'
[37m[3/10/2025, 12:14:55 PM] [39m[36m[Rudi][39m Initializing Roomba2 accessory...
[37m[3/10/2025, 12:14:55 PM] [39m[36m[Rosie][39m Initializing Roomba2 accessory...
[37m[3/10/2025, 12:24:45 PM] [39mRegistering accessory '@homebridge-plugins/homebridge-roomba.Roomba2'
[37m[3/10/2025, 12:24:45 PM] [39m[36m[Rudi][39m Initializing Roomba2 accessory...
[37m[3/10/2025, 12:24:45 PM] [39m[36m[Rosie][39m Initializing Roomba2 accessory...
```

### Config for homebridge-roomba

```shell
"accessories": [
        {
            "name": "Roomba",
            "email": "username",
            "password": "password",
            "devices": [
                {
                    "name": "Rosie",
                    "model": "j7",
                    "serialnum": "J710020B21120N101084",
                    "blid": "DCEED69E04F04788B5EAD38F6DEE227E",
                    "robotpwd": "device password",
                    "ipaddress": "192.168.xxx.xxx",
                    "dockContactSensor": true,
                    "runningContactSensor": true,
                    "binContactSensor": true,
                    "dockingContactSensor": true,
                    "homeSwitch": true,
                    "cleanBehaviour": "everywhere",
                    "mission": {
                        "ordered": 1,
                        "regions": [
                            {
                                "type": "rid",
                                "params": {
                                    "noAutoPasses": false,
                                    "twoPass": false
                                }
                            }
                        ]
                    },
                    "stopBehaviour": "home"
                },
                {
                    "name": "Rudi",
                    "model": "Braava jet m6",
                    "serialnum": "M611320B220526N208394",
                    "blid": "DCEED69E04F04788B5EAD38F6DEE227E",
                    "robotpwd": "devicepassword",
                    "ipaddress": "192.168.xxx.xxx",
                    "dockContactSensor": true,
                    "runningContactSensor": true,
                    "binContactSensor": true,
                    "dockingContactSensor": true,
                    "tankContactSensor": true,
                    "homeSwitch": true,
                    "cleanBehaviour": "everywhere",
                    "mission": {
                        "ordered": 1,
                        "regions": [
                            {
                                "type": "rid",
                                "params": {
                                    "noAutoPasses": false,
                                    "twoPass": false
                                }
                            }
                        ]
                    },
                    "stopBehaviour": "home"
                }
            ],
            "accessory": "Roomba2"
        },
```

### Node.js Version

v22.14.0

### NPM Version

v10.9.2

### Homebridge Version

v1.9.0

### Homebridge Roomba Plugin Version

v2.1.1

### Operating System

Docker

**Comment by coffeeandubuntu** [comment]
I am also having this issue.

**Comment by jlg89** [comment]
same as #162

**Comment by bmoffatt** [comment]
I believe the issue is the plugin placing the config in `"accessories": [` rather than `"platforms": [`, hinted at by the v2.0.0 release note `Change from Accessory base to Platform based Plugin`

I fixed this on my setup by editing the config.json, moving the accessories entry to the `"platforms"` list, and changing the field `"accessory": "Roomba2"` to `"platform": "Roomba"`

Touching the plugin config in the UI would bring back the bad `"accessories"` entry and the `No plugin was found for the accessory "Roomba2" in your config.json` error in the logs. However this stopped being reproducible sometime later, probably after an OS update and reboot.

**Comment by coffeeandubuntu** [comment]
I tried doing this, but it still doesn't seem to work for me. At this point version 1.5.3 works fine, but anything after that throws an error and won't enable the child bridge.

**Comment by mwcassens** [comment]
@bmoffatt Would you post the relevant section of the config.json that allowed your roomba accessories to connect with version 2.1 of the plugin?

**Comment by coffeeandubuntu** [comment]
Sure! Here you go:

        {
            "name": "CloudflaredTunnel",
            "email": "REDACTED",
            "password": "REDACTED",
            "devices": [
                {
                    "name": "Roomba",
                    "model": "+j9",
                    "blid": "REDACTED",
                    "robotpwd": "REDACTED",
                    "ipaddress": "192.168.2.83",
                    "dockContactSensor": true,
                    "cleanBehaviour": "everywhere",
                    "mission": {
                        "ordered": 1,
                        "regions": [
                            {
                                "type": "rid",
                                "params": {
                                    "noAutoPasses": false,
                                    "twoPass": false
                                }
                            }
                        ]
                    },
                    "stopBehaviour": "home"
                }
            ],
            "platform": "Roomba"
        }
    ],
    "disabledPlugins": [],
    "accessories": [
        {
            "name": "Roomba",
            "model": "+j9",
            "blid": "REDACTED",
            "robotpwd": "REDACTED",
            "ipaddress": "192.168.2.83",
            "dockContactSensor": true,
            "cleanBehaviour": "everywhere",
            "mission": {
                "ordered": 1,
                "regions": [
                    {
                        "type": "rid",
                        "params": {
                            "noAutoPasses": false,
                            "twoPass": false
                        }
                    }
                ]
            },
            "stopBehaviour": "home",
            "accessory": "Roomba2",
            "_bridge": {
                "username": "0E:52:9D:3A:2C:98",
                "port": 32138
            }
        }

**Comment by jlg89** [comment]
So the whole block has to be duplicated under accessories and devices?

**Comment by bmoffatt** [comment]
> @bmoffatt Would you post the relevant section of the config.json that allowed your roomba accessories to connect with version 2.1 of the plugin?

```
{
    "bridge": {
        ...
    },
    "accessories": [],
    "platforms": [
        ...,
        {
            "name": "Roomba",
            "email": "EMAIL",
            "password": "PASSWORD",
            "disableDiscovery": false,
            "idleWatchInterval": 1,
            "debug": true,
            "platform": "Roomba"
        }
    ],
    "disabledPlugins": [
        ...
    ]
}
```

**Comment by coffeeandubuntu** [comment]
Just to be clear — what I posted only works under 1.5.3. Not 2.1. I can’t get it working under 2.1.

**Comment by mwcassens** [comment]
@bmoffatt Thank you for posting the config.json file.  I can confirm that this works for me using version 2.1 of the Roomba plugin.

**Comment by jlg89** [comment]
I tried this, and the plugin will not find the iRobot device on the local network. It also insists upon having the iRobot username/password. Ended up uninstalling the plugin completely, had to manually remove it from the json. Now not even 1.5.3 will work. Giving up for the time being, I'll just use the iRobot app.

**Comment by brianysf** [comment]
Same issue. Reverting to 1.5.3 sort of worked but I'm having some strange behavior. Wish I hadn't switched to the Profiled plugin.

**Comment by javier-cr** [comment]
+1, also experiencing this on 2.1.0

**Comment by bwp91** [comment]
Thanks for the reports — and apologies this upgrade has been rough. Here's what's happening and how to fix it.

**Why the error appears**

The old 1.x plugin registered each Roomba as a Homebridge **accessory** (that's the `"accessory": "Roomba2"` entry in the `accessories` section of your `config.json`). The 2.x plugin is a **platform** instead. When you upgrade, that old accessory entry is left behind, and because no plugin provides an accessory called `Roomba2` any more, Homebridge logs:

> No plugin was found for the accessory "Roomba2"

The plugin itself is loading fine — it's the leftover config entry that's orphaned.

**The fix — remove the old entry and configure the platform**

1. Open your `config.json` (Homebridge UI → top-right menu → *Config*).
2. In the `"accessories"` array, delete any object with `"accessory": "Roomba2"`.
3. Make sure your Roomba is configured under `"platforms"` instead, with a block like:

```json
{
  "platform": "Roomba",
  "name": "Roomba",
  "email": "your-irobot-email",
  "password": "your-irobot-password"
}
```

(Or, for a fully local setup, use `disableDiscovery: true` with a `devices` array of `blid` / `password` / `ipaddress` — see the wiki once it's up.)

4. Save and restart Homebridge.

Your Roombas will then be discovered by the platform and the error will be gone. Your HomeKit automations should re-link once the accessories come back with the same names.

I'm closing this as the cause is understood and it's a config migration rather than a plugin bug — but please comment if the steps above don't clear it and I'll reopen. (Consolidating the duplicate reports of this same issue here.)

**Comment by jlg89** [comment]
This process is still not giving me a working setup. After step 4, the plugin recreates the "Roomba2" entry in config.json and deletes what I added to the "platforms" section. It also wiped out the child bridge config, I had that in a backup. The main issue may be that you also must add the "CloudflaredTunnel" portion of the JSON--thankfully, the entry that was re-added to the "accessories" array was properly formatted other than needing to change the "accessory": "Roomba2" line to "platform": "Roomba" (and add the child bridge config), so mostly a cut-and-paste. But even after all this, the plugin throws a message, "Skipping configuration for roomba: Roomba due to config" and the vac does not appear in HomeKit.

Given that updating from 1.5.3 completely breaks the plugin config, with the new version writing an incorrect JSON config into an incorrect spot in config.json, I'm going to very respectfully disagree that this is just a "config migration rather than a plugin bug." If nothing else, it is definitely a "breaking change" that should be prominently noted in the installation notes & readme.

```
{
    "name": "CloudflaredTunnel",
    "devices": [
        {
            "name": "Roomba",
            "model": "i3",
            "serialnum": "xxx",
            "blid": "xxx",
            "robotpwd": "xxx",
            "ipaddress": "192.168.33.10",
            "dockContactSensor": true,
            "runningContactSensor": true,
            "binContactSensor": true,
            "dockingContactSensor": true,
            "tankContactSensor": false,
            "homeSwitch": true,
            "cleanBehaviour": "everywhere",
            "mission": {
                "ordered": 1,
                "regions": [
                    {
                        "type": "rid",
                        "params": {
                            "noAutoPasses": false,
                            "twoPass": false
                        }
                    }
                ]
            },
            "stopBehaviour": "home",
            "externalAccessory": false
        }
    ],
    "disableDiscovery": true,
    "externalAccessory": false,
    "debug": false,
    "enableMatter": false,
    "email": "xxx",
    "password": "xxx",
    "_bridge": {
        "name": "Homebridge Roomba",
        "username": "0E:A3:F7:2C:D0:C1",
        "port": 56738
    },
    "platform": "Roomba"
}
```

(The Roomba does ping)
```
% ping 192.168.33.10
PING 192.168.33.10 (192.168.33.10): 56 data bytes
64 bytes from 192.168.33.10: icmp_seq=0 ttl=64 time=2.579 ms
64 bytes from 192.168.33.10: icmp_seq=1 ttl=64 time=4.490 ms
64 bytes from 192.168.33.10: icmp_seq=2 ttl=64 time=2.820 ms
64 bytes from 192.168.33.10: icmp_seq=3 ttl=64 time=2.373 ms
```

**Comment by bwp91** [comment]
@jlg89 You are right, and I was wrong to close this as just a config migration — thank you for pushing back. I dug into the code and manual mode (`disableDiscovery: true`) was genuinely broken, in two ways:

1. The plugin read your `devices` list, then skipped every entry with the exact message you saw — `Skipping configuration for roomba: Roomba due to config` — and never configured anything. Manual mode could not work for anyone.
2. Even without that, the manual entries store the password as `robotpwd` and the address as `ipaddress`, but the connection code was looking for fields named `password` and `ip` — so it would have tried to connect with no credentials.

**Both are fixed in v3.0.3-beta.0**, published just now. Install it via the Homebridge UI (plugin settings → **Alternate Versions** → 3.0.3-beta.0) or `npm install -g @homebridge-plugins/homebridge-roomba@beta`, then restart. Your config as posted should then work as-is — you can keep `disableDiscovery: true` with your email/password present, and your `devices` entry (`blid` / `robotpwd` / `ipaddress`) is exactly what the fix now reads.

Two small notes on the config you posted:

- The `"name": "CloudflaredTunnel"` line is only a display label so it does no harm, but I would rename it to `"Roomba"` to avoid confusion later.
- With `"cleanBehaviour": "everywhere"` the `mission` block is not used, so you can delete it if you want a tidier config.

On the config being rewritten: the plugin itself never writes to `config.json` — that only happens when a settings screen saves or a backup is restored. My best guess is the old 1.x plugin was still installed at that moment and its settings screen re-saved the old accessory entry. If it happens again on 3.x with the old plugin fully removed, please tell me because that would be something new.

And your wider point is taken: the 1.x → 2.x/3.x change is a breaking change and the docs did not say so properly. I am adding an "Upgrading from 1.x" section to the wiki installation page today.

Reopening this until you confirm the beta works.

**Comment by jlg89** [comment]
3.0.3-beta.0 seems to have done the trick. Thank you!

I think just treating the 1.x->2.x/3.x upgrade as a breaking change is the simplest approach. I'm sure you could fart around with the code enough to make the migration work automagically every time, but it may not be worth the hassle.

**Comment by mwcassens** [comment]
3.0.3-beta.0 worked for me as well.  See new issue 227 which may or may not be related to this beta release.

**Comment by bwp91** [comment]
Thanks for confirming — glad manual mode is working for you now.

@jlg89 this is the fix for your setup too (`v3.0.3-beta.0` or newer; **beta.1** is now out and also clears the "Config validation failed" warning in the settings page). Leaving this open until you've had a chance to confirm on your subnet setup, since yours was the harder case.

For anyone finding this later, the two bugs were: with discovery disabled the plugin skipped every configured robot outright, and manual entries store the password and address as `robotpwd`/`ipaddress` while the connection code was looking for `password`/`ip`.

**Comment by bwp91** [comment]
Two confirmations in, so I'll close this.

@jlg89 — apologies, my last comment asked you to confirm something you had already confirmed a few hours earlier. That was me not reading the thread properly, not you missing a step.

@mwcassens — thanks for the second confirmation, and for raising #227 separately rather than tacking it on here. That one turned out to be unrelated to the manual-mode fix and is already resolved.

The fix ships in **v3.0.3**. Until that's out, `@beta` has it.

For anyone finding this later: with `disableDiscovery: true` the plugin skipped every robot in your `devices` list outright, and manual entries store their credentials as `robotpwd` and `ipaddress` while the connection code was reading `password` and `ip`. Manual mode could not have worked for anybody. The 1.x to 2.x/3.x upgrade is also a genuine breaking change, and the wiki installation page now says so.

**Comment by bwp91** [comment]
**v3.0.3 is released** — manual mode is fixed in a full release now, no beta needed. Thanks again both.
